AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0ad21ae1d0696ad58
      KeyName: ins
      Tags:
        - Key: Name
          Value: MyEC2Instance
